# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3d3GaZOhUeLDNOS32Ivf9wsHOsJGAWQ

TT Project
"""

# -*- coding: utf-8 -*-
"""
Online Class Attendance Analysis Project
College: Rungta International Skill University, Bhilai
Dataset: 400 classes of 80 students each (32,000 records)
Author: Data Visualization Student
Course: Minor 1 - Data Visualization
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')
import matplotlib.dates as mdates
from scipy import stats
import calendar

# Set style for better visualizations
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# ============================================
# 1. GENERATE RUNGTA UNIVERSITY ATTENDANCE DATA
# ============================================

def generate_rungta_university_data(total_classes=400, total_students=80):
    """
    Generate attendance data for Rungta International Skill University, Bhilai
    """
    np.random.seed(42)

    # Current date setup (Indian timezone)
    current_date = datetime.now()
    start_date = current_date - timedelta(days=120)  # 4 months of data

    # Rungta University specific details
    college_name = "Rungta International Skill University"
    city = "Bhilai"
    state = "Chhattisgarh"

    # Rungta University common student names
    first_names = [
        'Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Reyansh', 'Mohit',
        'Aaradhya', 'Ananya', 'Diya', 'Ishita', 'Sara', 'Myra', 'Aadhya', 'Neha',
        'Rohan', 'Kabir', 'Ayaan', 'Advik', 'Prisha', 'Anika', 'Kiara', 'Ira',
        'Raj', 'Amit', 'Suresh', 'Priya', 'Sunita', 'Vikram', 'Meera', 'Kiran',
        'Sanjay', 'Ritu', 'Nikhil', 'Pooja', 'Rahul', 'Shreya', 'Vishal', 'Anjali',
        'Deepak', 'Swati', 'Gaurav', 'Madhu', 'Kunal', 'Tanvi', 'Harsh', 'Sonia',
        'Prateek', 'Rashmi', 'Vinod', 'Kavita', 'Manish', 'Ruchi', 'Siddharth', 'Tanya'
    ]

    last_names = [
        'Sharma', 'Verma', 'Patel', 'Singh', 'Kumar', 'Reddy', 'Das', 'Nair',
        'Gupta', 'Malhotra', 'Mehta', 'Joshi', 'Shah', 'Jain', 'Bose', 'Banerjee',
        'Choudhary', 'Mishra', 'Yadav', 'Rao', 'Chatterjee', 'Saxena', 'Tripathi',
        'Agrawal', 'Bhatt', 'Chauhan', 'Dubey', 'Gandhi', 'Iyer', 'Kapoor'
    ]

    # Rungta University departments and programs
    departments = [
        'Computer Science & Engineering',
        'Electronics & Communication',
        'Mechanical Engineering',
        'Civil Engineering',
        'Electrical Engineering',
        'Information Technology',
        'Business Administration',
        'Commerce',
        'Science',
        'Arts'
    ]

    # Rungta University subjects (skill-based)
    subjects = [
        'Programming Fundamentals',
        'Data Structures & Algorithms',
        'Database Management',
        'Web Development',
        'Mobile App Development',
        'Machine Learning',
        'Cloud Computing',
        'Cyber Security',
        'Digital Marketing',
        'Entrepreneurship',
        'Communication Skills',
        'Project Management',
        'IoT & Embedded Systems',
        'Robotics & Automation',
        'Renewable Energy',
        'Environmental Science',
        'Business Analytics',
        'Financial Accounting'
    ]

    # Rungta University classrooms
    classrooms = [
        'R-101', 'R-102', 'R-103', 'R-201', 'R-202', 'R-203',
        'S-101', 'S-102', 'S-103', 'T-101', 'T-102', 'T-103'
    ]

    # Rungta University faculty
    faculty_members = [
        'Dr. R.K. Sharma',
        'Prof. S. Verma',
        'Dr. A. Patel',
        'Prof. M. Singh',
        'Dr. P. Gupta',
        'Prof. R. Reddy',
        'Dr. S. Joshi',
        'Prof. K. Malhotra'
    ]

    # Generate 80 unique Rungta University students
    students = []
    student_ids = []

    for i in range(total_students):
        first = np.random.choice(first_names)
        last = np.random.choice(last_names)
        department = np.random.choice(departments)

        # Student attributes specific to Rungta University
        academic_year = np.random.choice(['1st Year', '2nd Year', '3rd Year', '4th Year'],
                                        p=[0.25, 0.25, 0.25, 0.25])

        # Device usage patterns at Rungta University
        devices = ['Laptop', 'Mobile', 'Tablet', 'Desktop']
        device_probs = [0.45, 0.35, 0.15, 0.05]  # More laptops in university
        device = np.random.choice(devices, p=device_probs)

        # Internet connectivity in Bhilai
        internet_types = ['WiFi', 'Mobile Data', 'Broadband', 'Campus WiFi']
        internet_probs = [0.3, 0.4, 0.2, 0.1]  # Rungta University campus WiFi available
        internet = np.random.choice(internet_types, p=internet_probs)

        # Student performance category
        performance_levels = ['Excellent', 'Good', 'Average', 'Needs Improvement']
        performance = np.random.choice(performance_levels, p=[0.2, 0.4, 0.3, 0.1])

        # Attendance tendency based on performance
        attendance_base = {
            'Excellent': 0.90,
            'Good': 0.80,
            'Average': 0.70,
            'Needs Improvement': 0.55
        }[performance]

        student_id = f'RISU{str(i+1).zfill(3)}'
        student_ids.append(student_id)

        students.append({
            'student_id': student_id,
            'name': f'{first} {last}',
            'department': department,
            'academic_year': academic_year,
            'device': device,
            'internet_type': internet,
            'performance_level': performance,
            'attendance_base': attendance_base,
            'engagement_factor': np.random.beta(5, 2),  # Random engagement factor
            'hostel_student': np.random.choice([True, False], p=[0.4, 0.6]),  # 40% hostelites
            'scholarship': np.random.choice(['Yes', 'No'], p=[0.3, 0.7])  # 30% scholarship
        })

    # Generate 400 class records for Rungta University
    data = []
    class_counter = 0

    # Create date range (avoid major holidays)
    date_range = pd.date_range(start=start_date, end=current_date, freq='D')

    # Rungta University academic calendar factors
    holiday_dates = [
        '2024-01-26',  # Republic Day
        '2024-03-25',  # Holi (approximate)
        '2024-08-15',  # Independence Day
        '2024-10-02',  # Gandhi Jayanti
        '2024-12-25',  # Christmas
    ]

    for current_date_obj in date_range:
        date_str = current_date_obj.date()
        day_name = current_date_obj.strftime('%A')
        week_num = current_date_obj.isocalendar()[1]
        month = current_date_obj.month
        month_name = current_date_obj.strftime('%B')

        # Skip if it's a holiday
        if date_str.strftime('%Y-%m-%d') in holiday_dates:
            continue

        # Skip most Sundays (university usually closed)
        if day_name == 'Sunday' and np.random.random() < 0.8:
            continue

        # Day-specific factors for Rungta University
        day_factors = {
            'Monday': 0.85,    # Start of week
            'Tuesday': 0.92,   # Regular day
            'Wednesday': 0.95, # Mid-week peak
            'Thursday': 0.90,  # Regular day
            'Friday': 0.88,    # Weekend approaching
            'Saturday': 0.75,  # Weekend classes (some departments)
            'Sunday': 0.65     # Rare classes
        }
        day_factor = day_factors.get(day_name, 1.0)

        # Seasonal factors for Bhilai climate
        if month in [3, 4, 5]:  # Summer (hot in Bhilai)
            season_factor = 0.88
        elif month in [6, 7, 8, 9]:  # Monsoon
            season_factor = 0.85  # Rain affects connectivity
        elif month in [10, 11]:  # Post-monsoon/Diwali season
            season_factor = 0.82  # Festive season
        else:  # Winter (Dec-Feb)
            season_factor = 0.92  # Pleasant weather

        # Generate 3-5 classes per day (university schedule)
        classes_today = np.random.randint(3, 6)

        for class_num in range(classes_today):
            if class_counter >= total_classes:
                break

            class_counter += 1
            class_id = f'RISU-CLS{str(class_counter).zfill(4)}'

            # Class time (Rungta University timings: 9 AM to 5 PM)
            class_hour = np.random.choice([9, 10, 11, 12, 14, 15, 16])
            class_time = f'{class_hour:02d}:00'

            # Subject (skill-based at RISU)
            subject = np.random.choice(subjects)

            # Faculty member
            faculty = np.random.choice(faculty_members)

            # Classroom
            classroom = np.random.choice(classrooms)

            # Class duration (50-75 minutes, university standard)
            duration = np.random.choice([50, 60, 75])

            # Class type at skill university
            class_type = np.random.choice(['Lecture', 'Lab', 'Tutorial', 'Workshop', 'Project'],
                                         p=[0.4, 0.25, 0.15, 0.15, 0.05])

            # Time of day factor for Bhilai
            if class_hour < 10:
                time_factor = 0.88  # Early morning
            elif class_hour < 12:
                time_factor = 0.95  # Late morning (best)
            elif class_hour < 15:
                time_factor = 0.90  # Afternoon
            else:
                time_factor = 0.85  # Late afternoon

            # Generate attendance for all 80 students
            for student in students:
                # Base attendance probability
                base_prob = student['attendance_base']

                # Apply factors
                attendance_prob = base_prob * day_factor * season_factor * time_factor

                # Subject popularity factor
                subject_popularity = {
                    'Programming Fundamentals': 0.95,
                    'Machine Learning': 0.97,
                    'Web Development': 0.96,
                    'Cyber Security': 0.98,
                    'Entrepreneurship': 0.94,
                    'Communication Skills': 0.92,
                    'Financial Accounting': 0.88,
                    'Environmental Science': 0.90
                }
                subj_factor = subject_popularity.get(subject, 0.93)
                attendance_prob *= subj_factor

                # Class type factor
                type_factors = {
                    'Lecture': 0.92,
                    'Lab': 0.96,  # Labs have higher attendance
                    'Tutorial': 0.94,
                    'Workshop': 0.98,  # Workshops are popular
                    'Project': 0.99  # Project classes have highest attendance
                }
                attendance_prob *= type_factors[class_type]

                # Hostel student factor
                if student['hostel_student']:
                    attendance_prob *= 1.05  # Hostel students have better attendance

                # Scholarship student factor
                if student['scholarship'] == 'Yes':
                    attendance_prob *= 1.08  # Scholarship students maintain attendance

                # Random variation
                attendance_prob *= np.random.uniform(0.85, 1.15)
                attendance_prob = min(0.99, max(0.15, attendance_prob))

                # Determine attendance
                attended = 1 if np.random.random() < attendance_prob else 0

                # Generate detailed metrics if attended
                if attended:
                    login_duration = np.random.normal(duration * 0.85, duration * 0.15)
                    login_duration = max(15, min(duration, login_duration))

                    # Engagement metrics for skill university
                    interactions = int(np.random.poisson(4 + student['engagement_factor'] * 8))
                    questions_asked = int(np.random.poisson(student['engagement_factor'] * 4))
                    assignment_submitted = 1 if np.random.random() < 0.9 else 0
                    poll_participation = 1 if np.random.random() < 0.8 else 0

                    # Performance metrics
                    quiz_score = np.random.normal(65 + attendance_prob * 25, 10)
                    quiz_score = max(0, min(100, quiz_score))

                    # Practical skill assessment (for skill university)
                    practical_score = np.random.normal(70 + student['engagement_factor'] * 20, 15)
                    practical_score = max(0, min(100, practical_score))

                    # Connectivity metrics
                    connection_quality = np.random.choice(['Excellent', 'Good', 'Fair', 'Poor'],
                                                         p=[0.5, 0.3, 0.15, 0.05])  # Good campus connectivity
                    video_on = 1 if np.random.random() < 0.9 else 0
                    audio_on = 1 if np.random.random() < 0.95 else 0

                else:
                    login_duration = 0
                    interactions = 0
                    questions_asked = 0
                    assignment_submitted = 0
                    poll_participation = 0
                    quiz_score = 0
                    practical_score = 0
                    connection_quality = 'N/A'
                    video_on = 0
                    audio_on = 0

                data.append({
                    'college': college_name,
                    'city': city,
                    'state': state,

                    'class_id': class_id,
                    'class_number': class_counter,
                    'date': date_str,
                    'datetime': current_date_obj.replace(hour=class_hour, minute=0),
                    'day_name': day_name,
                    'week_number': week_num,
                    'month': month,
                    'month_name': month_name,
                    'class_time': class_time,
                    'class_hour': class_hour,
                    'subject': subject,
                    'faculty': faculty,
                    'classroom': classroom,
                    'class_type': class_type,
                    'duration_minutes': duration,

                    'student_id': student['student_id'],
                    'student_name': student['name'],
                    'department': student['department'],
                    'academic_year': student['academic_year'],
                    'device': student['device'],
                    'internet_type': student['internet_type'],
                    'performance_level': student['performance_level'],
                    'hostel_student': student['hostel_student'],
                    'scholarship': student['scholarship'],

                    'attended': attended,
                    'login_duration_min': login_duration,
                    'interactions': interactions,
                    'questions_asked': questions_asked,
                    'assignment_submitted': assignment_submitted,
                    'poll_participation': poll_participation,
                    'quiz_score': quiz_score,
                    'practical_score': practical_score,
                    'connection_quality': connection_quality,
                    'video_on': video_on,
                    'audio_on': audio_on,

                    'attendance_probability': attendance_prob
                })

    df = pd.DataFrame(data)

    # Calculate derived metrics
    df['total_score'] = (df['quiz_score'] * 0.6 + df['practical_score'] * 0.4)
    df['engagement_score'] = df['interactions'] + df['questions_asked'] * 2 + df['poll_participation'] * 3

    # Performance categories
    conditions = [
        df['total_score'] >= 85,
        df['total_score'] >= 70,
        df['total_score'] >= 60,
        df['total_score'] >= 50,
        df['total_score'] < 50
    ]
    choices = ['Distinction', 'First Class', 'Second Class', 'Pass', 'Fail']
    df['performance_category'] = np.select(conditions, choices, default='Pass')

    print(f"\nRUNGTA UNIVERSITY DATASET GENERATION COMPLETE!")
    print("=" * 70)
    print(f"College: {college_name}")
    print(f"Location: {city}, {state}")
    print(f"Total classes: {df['class_id'].nunique()}")
    print(f"Total students: {df['student_id'].nunique()}")
    print(f"Total records: {len(df):,}")
    print(f"Date range: {df['date'].min()} to {df['date'].max()}")
    print(f"Departments: {df['department'].nunique()}")
    print(f"Subjects: {df['subject'].nunique()}")
    print(f"Faculty members: {df['faculty'].nunique()}")

    return df

# Generate the dataset
print("=" * 70)
print("RUNGTA INTERNATIONAL SKILL UNIVERSITY, BHILAI")
print("ATTENDANCE ANALYSIS DATASET GENERATION")
print("400 Classes | 80 Students | 32,000 Records")
print("=" * 70)

df = generate_rungta_university_data(total_classes=400, total_students=80)

# ============================================
# 2. COMPREHENSIVE DESCRIPTIVE STATISTICS
# ============================================

def calculate_rungta_statistics(df):
    """
    Calculate comprehensive statistics for Rungta University
    """
    print("\n" + "=" * 70)
    print("RUNGTA UNIVERSITY - DESCRIPTIVE STATISTICS")
    print("=" * 70)

    # 1. University Overview
    print("\n1. UNIVERSITY OVERVIEW")
    print("-" * 50)

    total_classes = df['class_id'].nunique()
    total_records = len(df)
    total_attended = df['attended'].sum()
    overall_rate = total_attended / total_records * 100

    print(f"Institution: {df['college'].iloc[0]}")
    print(f"Location: {df['city'].iloc[0]}, {df['state'].iloc[0]}")
    print(f"Total Classes Conducted: {total_classes}")
    print(f"Total Attendance Records: {total_records:,}")
    print(f"Classes Attended: {total_attended:,}")
    print(f"Overall Attendance Rate: {overall_rate:.2f}%")
    print(f"Average Login Duration: {df[df['attended']==1]['login_duration_min'].mean():.1f} minutes")
    print(f"Average Total Score: {df[df['attended']==1]['total_score'].mean():.1f}/100")

    # 2. Daily Attendance Patterns
    print("\n2. DAILY ATTENDANCE PATTERNS")
    print("-" * 50)

    daily_stats = df.groupby('day_name').agg({
        'attended': 'mean',
        'login_duration_min': 'mean',
        'interactions': 'mean',
        'total_score': 'mean'
    }).round(3)

    # Reorder days
    day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    daily_stats = daily_stats.reindex(day_order)
    daily_stats['attended'] = daily_stats['attended'] * 100

    for day, row in daily_stats.iterrows():
        if day in day_order[:6]:  # Only weekdays + Saturday
            print(f"{day:10} - Attendance: {row['attended']:5.1f}% | "
                  f"Duration: {row['login_duration_min']:4.1f} min | "
                  f"Score: {row['total_score']:4.1f}")

    # 3. Department-wise Analysis
    print("\n3. DEPARTMENT-WISE ANALYSIS")
    print("-" * 50)

    dept_stats = df.groupby('department').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'practical_score': 'mean',
        'student_id': 'nunique',
        'class_id': 'nunique'
    }).round(2)

    dept_stats['attended'] = dept_stats['attended'] * 100
    dept_stats = dept_stats.sort_values('attended', ascending=False)

    print(f"{'Department':30} {'Attend %':10} {'Avg Score':10} {'Students':10} {'Classes':10}")
    print("-" * 80)
    for dept, row in dept_stats.iterrows():
        print(f"{dept[:28]:30} {row['attended']:9.1f}% {row['total_score']:9.1f} "
              f"{int(row['student_id']):10d} {int(row['class_id']):10d}")

    # 4. Academic Year Analysis
    print("\n4. ACADEMIC YEAR ANALYSIS")
    print("-" * 50)

    year_stats = df.groupby('academic_year').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'interactions': 'mean',
        'student_id': 'nunique'
    }).round(2)

    year_stats['attended'] = year_stats['attended'] * 100

    for year, row in year_stats.iterrows():
        print(f"{year:10} - Attendance: {row['attended']:5.1f}% | "
              f"Avg Score: {row['total_score']:5.1f} | "
              f"Interactions: {row['interactions']:4.1f} | "
              f"Students: {int(row['student_id']):3d}")

    # 5. Subject-wise Analysis (Top 10)
    print("\n5. TOP 10 SUBJECTS BY ATTENDANCE")
    print("-" * 50)

    subject_stats = df.groupby('subject').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'practical_score': 'mean',
        'class_id': 'nunique'
    }).round(2)

    subject_stats['attended'] = subject_stats['attended'] * 100
    subject_stats = subject_stats.sort_values('attended', ascending=False).head(10)

    for subject, row in subject_stats.iterrows():
        print(f"{subject:30} - Attendance: {row['attended']:5.1f}% | "
              f"Score: {row['total_score']:5.1f} | "
              f"Practical: {row['practical_score']:5.1f}")

    # 6. Faculty Performance
    print("\n6. FACULTY PERFORMANCE ANALYSIS")
    print("-" * 50)

    faculty_stats = df.groupby('faculty').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'engagement_score': 'mean',
        'class_id': 'nunique'
    }).round(2)

    faculty_stats['attended'] = faculty_stats['attended'] * 100
    faculty_stats = faculty_stats.sort_values('attended', ascending=False)

    for faculty, row in faculty_stats.iterrows():
        print(f"{faculty:20} - Attendance: {row['attended']:5.1f}% | "
              f"Score: {row['total_score']:5.1f} | "
              f"Classes: {int(row['class_id']):3d}")

    # 7. Technology & Infrastructure
    print("\n7. TECHNOLOGY & INFRASTRUCTURE ANALYSIS")
    print("-" * 50)

    print("Device Usage:")
    device_stats = df.groupby('device').agg({
        'attended': 'mean',
        'connection_quality': lambda x: (x == 'Excellent').mean(),
        'student_id': 'nunique'
    }).round(3)

    device_stats['attended'] = device_stats['attended'] * 100
    device_stats['connection_quality'] = device_stats['connection_quality'] * 100

    for device, row in device_stats.iterrows():
        print(f"  {device:10} - Attendance: {row['attended']:5.1f}% | "
              f"Good Connection: {row['connection_quality']:4.1f}% | "
              f"Users: {int(row['student_id']):3d}")

    print("\nInternet Connectivity:")
    internet_stats = df.groupby('internet_type').agg({
        'attended': 'mean',
        'connection_quality': lambda x: (x == 'Excellent').mean()
    }).round(3)

    internet_stats['attended'] = internet_stats['attended'] * 100
    internet_stats['connection_quality'] = internet_stats['connection_quality'] * 100

    for internet, row in internet_stats.iterrows():
        print(f"  {internet:15} - Attendance: {row['attended']:5.1f}% | "
              f"Good Connection: {row['connection_quality']:4.1f}%")

    # 8. Hostel vs Day Scholar
    print("\n8. HOSTEL vs DAY SCHOLAR ANALYSIS")
    print("-" * 50)

    hostel_stats = df.groupby('hostel_student').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'login_duration_min': 'mean'
    }).round(2)

    hostel_stats['attended'] = hostel_stats['attended'] * 100

    for hostel, row in hostel_stats.iterrows():
        status = "Hostel Student" if hostel else "Day Scholar"
        print(f"{status:20} - Attendance: {row['attended']:5.1f}% | "
              f"Score: {row['total_score']:5.1f} | "
              f"Duration: {row['login_duration_min']:5.1f} min")

    # 9. Scholarship Impact
    print("\n9. SCHOLARSHIP IMPACT ANALYSIS")
    print("-" * 50)

    scholarship_stats = df.groupby('scholarship').agg({
        'attended': 'mean',
        'total_score': 'mean',
        'assignment_submitted': 'mean'
    }).round(2)

    scholarship_stats['attended'] = scholarship_stats['attended'] * 100
    scholarship_stats['assignment_submitted'] = scholarship_stats['assignment_submitted'] * 100

    for scholarship, row in scholarship_stats.iterrows():
        print(f"Scholarship: {scholarship:5} - Attendance: {row['attended']:5.1f}% | "
              f"Score: {row['total_score']:5.1f} | "
              f"Assignments: {row['assignment_submitted']:5.1f}%")

    # 10. Class Type Analysis
    print("\n10. CLASS TYPE EFFECTIVENESS")
    print("-" * 50)

    class_type_stats = df.groupby('class_type').agg({
        'attended': 'mean',
        'engagement_score': 'mean',
        'practical_score': 'mean',
        'class_id': 'nunique'
    }).round(2)

    class_type_stats['attended'] = class_type_stats['attended'] * 100

    for ctype, row in class_type_stats.iterrows():
        print(f"{ctype:15} - Attendance: {row['attended']:5.1f}% | "
              f"Engagement: {row['engagement_score']:5.1f} | "
              f"Practical: {row['practical_score']:5.1f}")

    return daily_stats, dept_stats, subject_stats, faculty_stats

# Calculate statistics
daily_stats, dept_stats, subject_stats, faculty_stats = calculate_rungta_statistics(df)

# ============================================
# 3. ADVANCED VISUALIZATIONS FOR RUNGTA UNIVERSITY
# ============================================

print("\n" + "=" * 70)
print("GENERATING RUNGTA UNIVERSITY VISUALIZATION DASHBOARD")
print("=" * 70)

# Create comprehensive dashboard
fig = plt.figure(figsize=(24, 20))

# 1. Daily Attendance Trend (Line Plot)
ax1 = plt.subplot(4, 4, 1)
daily_trend = df.groupby('date')['attended'].mean() * 100
daily_trend.plot(ax=ax1, color='#1E3F66', linewidth=2.5, alpha=0.8)  # Rungta blue
ax1.set_title('Daily Attendance Trend\nRungta University, Bhilai', fontsize=14, fontweight='bold')
ax1.set_xlabel('Date', fontsize=12)
ax1.set_ylabel('Attendance Rate (%)', fontsize=12)
ax1.tick_params(axis='x', rotation=45)
ax1.grid(True, alpha=0.3)

# Add 7-day moving average
rolling_avg = daily_trend.rolling(window=7, min_periods=1).mean()
ax1.plot(rolling_avg.index, rolling_avg.values, 'r--', linewidth=2.5,
         label='7-day Moving Average')
ax1.legend(loc='upper left', fontsize=10)

# 2. Weekly Pattern (Line Plot)
ax2 = plt.subplot(4, 4, 2)
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
daily_plot_data = daily_stats.reindex(day_order)

ax2.plot(daily_plot_data.index, daily_plot_data['attended'],
         marker='o', markersize=8, linewidth=3, color='#2E8B57')  # Sea green
ax2.set_title('Weekly Attendance Pattern', fontsize=14, fontweight='bold')
ax2.set_xlabel('Day of Week', fontsize=12)
ax2.set_ylabel('Attendance Rate (%)', fontsize=12)
ax2.grid(True, alpha=0.3)
ax2.tick_params(axis='x', rotation=45)

# Add value labels
for i, (day, rate) in enumerate(zip(daily_plot_data.index, daily_plot_data['attended'])):
    ax2.text(i, rate + 0.5, f'{rate:.1f}%', ha='center', va='bottom',
             fontsize=10, fontweight='bold')

# 3. Department-wise Attendance (Bar Plot)
ax3 = plt.subplot(4, 4, 3)
dept_attendance = dept_stats['attended'].sort_values(ascending=True)

colors = plt.cm.viridis(np.linspace(0.2, 0.8, len(dept_attendance)))
bars = ax3.barh(range(len(dept_attendance)), dept_attendance.values, color=colors)
ax3.set_yticks(range(len(dept_attendance)))
ax3.set_yticklabels([dept[:20] + '...' if len(dept) > 20 else dept
                    for dept in dept_attendance.index])
ax3.set_xlabel('Attendance Rate (%)', fontsize=12)
ax3.set_title('Department-wise Attendance', fontsize=14, fontweight='bold')
ax3.grid(True, alpha=0.3, axis='x')

# Add value labels
for i, v in enumerate(dept_attendance.values):
    ax3.text(v + 0.3, i, f'{v:.1f}%', va='center', fontsize=9)

# 4. Academic Year Comparison (Grouped Bar Plot)
ax4 = plt.subplot(4, 4, 4)
year_comparison = df.groupby('academic_year').agg({
    'attended': 'mean',
    'total_score': 'mean',
    'engagement_score': 'mean'
})

year_comparison['attended'] = year_comparison['attended'] * 100

x = np.arange(len(year_comparison))
width = 0.25

bars1 = ax4.bar(x - width, year_comparison['attended'], width,
                label='Attendance %', color='#1E3F66', alpha=0.8)
bars2 = ax4.bar(x, year_comparison['total_score'], width,
                label='Avg Score', color='#2E8B57', alpha=0.8)
bars3 = ax4.bar(x + width, year_comparison['engagement_score'], width,
                label='Engagement', color='#D4AF37', alpha=0.8)

ax4.set_xlabel('Academic Year', fontsize=12)
ax4.set_ylabel('Score', fontsize=12)
ax4.set_title('Academic Year Performance Comparison', fontsize=14, fontweight='bold')
ax4.set_xticks(x)
ax4.set_xticklabels(year_comparison.index)
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3, axis='y')

# 5. Subject Popularity (Horizontal Bar Plot)
ax5 = plt.subplot(4, 4, 5)
top_subjects = subject_stats.head(8).sort_values('attended', ascending=True)

y_pos = np.arange(len(top_subjects))
ax5.barh(y_pos, top_subjects['attended'],
         color=plt.cm.coolwarm(np.linspace(0.2, 0.8, len(top_subjects))))
ax5.set_yticks(y_pos)
ax5.set_yticklabels([subj[:25] + '...' if len(subj) > 25 else subj
                    for subj in top_subjects.index])
ax5.set_xlabel('Attendance Rate (%)', fontsize=12)
ax5.set_title('Top Subjects by Attendance', fontsize=14, fontweight='bold')
ax5.grid(True, alpha=0.3, axis='x')

# Add value labels
for i, v in enumerate(top_subjects['attended']):
    ax5.text(v + 0.3, i, f'{v:.1f}%', va='center', fontsize=9)

# 6. Faculty Performance (Bar Plot)
ax6 = plt.subplot(4, 4, 6)
faculty_performance = faculty_stats['attended'].sort_values(ascending=True)

colors = plt.cm.plasma(np.linspace(0.2, 0.8, len(faculty_performance)))
bars = ax6.barh(range(len(faculty_performance)), faculty_performance.values, color=colors)
ax6.set_yticks(range(len(faculty_performance)))
ax6.set_yticklabels([faculty.split()[-1] for faculty in faculty_performance.index])
ax6.set_xlabel('Attendance Rate (%)', fontsize=12)
ax6.set_title('Faculty Performance (by Attendance)', fontsize=14)